[2021-03-12 11:09:47,262] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: conversion_flow.taskPrepare 2021-03-12T11:09:46+00:00 [queued]>
[2021-03-12 11:09:47,270] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: conversion_flow.taskPrepare 2021-03-12T11:09:46+00:00 [queued]>
[2021-03-12 11:09:47,270] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-12 11:09:47,270] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-12 11:09:47,270] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-12 11:09:47,275] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): taskPrepare> on 2021-03-12T11:09:46+00:00
[2021-03-12 11:09:47,276] {standard_task_runner.py:52} INFO - Started process 1006 to run task
[2021-03-12 11:09:47,278] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'conversion_flow', 'taskPrepare', '2021-03-12T11:09:46+00:00', '--job-id', '4', '--pool', 'default_pool', '--raw', '--subdir', '/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/dag/conversion_flow.py', '--cfg-path', '/tmp/tmpiomivd4w', '--error-file', '/tmp/tmp_i9vlgg0']
[2021-03-12 11:09:47,279] {standard_task_runner.py:77} INFO - Job 4: Subtask taskPrepare
[2021-03-12 11:09:47,302] {logging_mixin.py:104} INFO - Running <TaskInstance: conversion_flow.taskPrepare 2021-03-12T11:09:46+00:00 [running]> on host 6299f34f884f
[2021-03-12 11:09:47,327] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=conversion_flow
AIRFLOW_CTX_TASK_ID=taskPrepare
AIRFLOW_CTX_EXECUTION_DATE=2021-03-12T11:09:46+00:00
AIRFLOW_CTX_DAG_RUN_ID=conversion_flow1615547386.409436
[2021-03-12 11:09:47,519] {python.py:118} INFO - Done. Returned value was: True
[2021-03-12 11:09:47,533] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=conversion_flow, task_id=taskPrepare, execution_date=20210312T110946, start_date=20210312T110947, end_date=20210312T110947
[2021-03-12 11:09:47,551] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-12 11:09:47,570] {local_task_job.py:146} INFO - Task exited with return code 0
